version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: data_pipeline_db
    restart: always
    environment:
      MYSQL_DATABASE: t1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db