apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: data-pipeline-app
    newName: 854745312525.dkr.ecr.eu-west-1.amazonaws.com/data-pipeline-app
    newTag: 8d778173bf788ee856fea8019a33cc87754900a5
