apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -v1
images:
  - name: data-pipeline-app
    newName: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/data-pipeline-app
    newTag: v1 # 초기 배포 시 사용할 태그
