apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: data-pipeline-rollout
spec:
  strategy:
    canary:
      canaryService: data-pipeline-svc-canary-v1
      stableService: data-pipeline-svc-stable-v1
      trafficRouting:
        alb:
          ingress: data-pipeline-ingress-v1
