apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AnalysisTemplate
      name: data-pipeline-canary
    path: patch-analysis-template-cloudwatch.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: data-pipeline-rollout
    path: patch-rollout-alb-args.yaml
