apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-validation
resources:
  - ../../base
components:
  - ../../components/alb-canary-gate
images:
  - name: data-pipeline-app
    newName: 854745312525.dkr.ecr.eu-west-1.amazonaws.com/data-pipeline-app
    newTag: e426d8db675e62e9ac55b5ba6ab913e05114b767
    digest: sha256:7a317a9de5b7d4c839c80f4b764242b2abb4a743a48018c633472d59ee93f158
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: data-pipeline-rollout
    path: patch-rollout.yaml
  - path: patch-migration.yaml
  - path: patch-cronjob.yaml
  - path: exclude-platform-ingress.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AnalysisTemplate
      name: data-pipeline-canary
    path: patch-prometheus.yaml
