apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-pipeline-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  ingressClassName: alb
spec:  
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
		name: data-pipeline-svc-stable
                port: { number: 80 }
