apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service-canary.yaml
  - service-stable.yaml
  - hpa.yaml
  - ingress.yaml
  - cronjob.yaml
  - db-migration-job.yaml
  - service-monitors.yaml
  - prometheus-rules.yaml
  - analysis-template.yaml
  - grafana-dashboard.yaml
