name: Build and Update Manifest

on:
  push:
    branches: [ "cicd_test" ]
    paths: [ "app/**", "Dockerfile", "k8s/**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/data-pipeline-app:$IMAGE_TAG .
          docker push $ECR_REGISTRY/data-pipeline-app:$IMAGE_TAG

      - name: Update Kustomize Tag
        run: |
          cd k8s/overlays/prod
          kustomize edit set image data-pipeline-app=${{ steps.login-ecr.outputs.registry }}/data-pipeline-app:${{ github.sha }}

      - name: Commit and Push Manifest Change
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add k8s/overlays/prod/kustomization.yaml
          git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
          git push origin cicd_test
